FROM golang:1.15-alpine3.14 as build

WORKDIR /go/amadeus

COPY . .

RUN apk update && \
  apk add --no-cache git curl && \
  go get -u github.com/cosmtrek/air && \
  go build -o /go/bin/air github.com/cosmtrek/air && \
  go get -u github.com/go-delve/delve/cmd/dlv && \
  go build -o /go/bin/dlv github.com/go-delve/delve/cmd/dlv

ENTRYPOINT ["./entrypoint.sh"]
